---
title: "nichenet_scaffold"
author: "Ryan Rebernick"
date: "3/1/2021"
output: html_document
---

# Load packages and data
```{r, message=F, warning=F}
library('plyr')
library('dplyr')
library('magrittr')
library('stringr')
library('data.table')
#devtools::install_github("saeyslab/nichenetr")
library('nichenetr')
library('Seurat')
library('tidyverse')
library('gplots')

load('/nfs/turbo/umms-csriram/scampit/Ryan/Projects/Dorothea/data/pmn.Robj')

```


# Select scaffold and subset based on cell type
```{r}

# select scaffold and show initial clustering of scaffold subset in context of all data
scaf <- subset(pmn, subset = Tissue == 'scaffold')
scaf$cellType <- Idents(scaf)
DimPlot(scaf, reduction = "umap")

# Add metadata
scaf$dxHl <- ifelse(grepl('\\.h\\.', scaf$sample), 'Hlthy', 'Dx')


granulocytes <- subset(scaf, subset = cellType == 'Granulocytes')
macrophages <- subset(scaf, subset = cellType == 'Macrophages')
dendritic <- subset(scaf, subset = cellType == 'Dendritic Cells')
fibroblasts <-subset(scaf, subset = cellType == 'Fibroblasts')
tcells <-subset(scaf, subset = cellType == 'T Cells')
nkcells <-subset(scaf, subset = cellType == 'NK Cells')
monocytes <-subset(scaf, subset = cellType == 'Monocytes')


```


# Load data necessary to run nichenet
```{r}
# Ligand target
ligand_target_matrix = readRDS(url("https://zenodo.org/record/3260758/files/ligand_target_matrix.rds"))

# Ligand receptor
lr_network = readRDS(url("https://zenodo.org/record/3260758/files/lr_network.rds"))

# weighted integrated network
weighted_networks = readRDS(url("https://zenodo.org/record/3260758/files/weighted_networks.rds"))


```

# Granulocytes
```{r}

Idents(scaf) <- scaf$cellType
nichenet_output = nichenet_seuratobj_aggregate(
  seurat_obj = scaf, 
  receiver = "Granulocytes", 
  condition_colname = "dxHl", condition_oi = "Dx", condition_reference = "Hlthy", 
  sender = "all", 
  ligand_target_matrix = ligand_target_matrix, lr_network = lr_network, weighted_networks = weighted_networks, organism = "mouse")

# plot target heatmap
nichenet_output$ligand_activity_target_heatmap

# Receptor interactions
nichenet_output$ligand_receptor_heatmap

# plot expression of ligands across celltypes by condition
DotPlot(scaf, features = nichenet_output$top_ligands %>% rev(), split.by = "dxHl", dot.min = .1) + RotatedAxis()

# plot expression of receptors across celltypes by condition
Idents(granulocytes) <- granulocytes$cellType
DotPlot(granulocytes, features = nichenet_output$top_receptors %>% rev(), group.by = "dxHl", dot.min = .1) + RotatedAxis()

```

# Macrophages
```{r}

Idents(scaf) <- scaf$cellType
nichenet_output = nichenet_seuratobj_aggregate(
  seurat_obj = scaf, 
  receiver = "Macrophages", 
  condition_colname = "dxHl", condition_oi = "Dx", condition_reference = "Hlthy", 
  sender = "all", 
  ligand_target_matrix = ligand_target_matrix, lr_network = lr_network, weighted_networks = weighted_networks, organism = "mouse")

# plot target heatmap
nichenet_output$ligand_activity_target_heatmap

# Receptor interactions
nichenet_output$ligand_receptor_heatmap

# plot expression of ligands across celltypes by condition
DotPlot(scaf, features = nichenet_output$top_ligands %>% rev(), split.by = "dxHl", dot.min = .1) + RotatedAxis()

# plot expression of receptors across celltypes by condition
Idents(macrophages) <- macrophages$cellType
DotPlot(macrophages, features = nichenet_output$top_receptors %>% rev(), group.by = "dxHl", dot.min = .1) + RotatedAxis()

```


# Dendritic cells   
```{r}

Idents(scaf) <- scaf$cellType
nichenet_output = nichenet_seuratobj_aggregate(
  seurat_obj = scaf, 
  receiver = "Dendritic Cells", 
  condition_colname = "dxHl", condition_oi = "Dx", condition_reference = "Hlthy", 
  sender = "all", 
  ligand_target_matrix = ligand_target_matrix, lr_network = lr_network, weighted_networks = weighted_networks, organism = "mouse")

# plot target heatmap
nichenet_output$ligand_activity_target_heatmap

# Receptor interactions
nichenet_output$ligand_receptor_heatmap

# plot expression of ligands across celltypes by condition
DotPlot(scaf, features = nichenet_output$top_ligands %>% rev(), split.by = "dxHl", dot.min = .1) + RotatedAxis()

# plot expression of receptors across celltypes by condition
Idents(dendritic) <- dendritic$cellType
DotPlot(dendritic, features = nichenet_output$top_receptors %>% rev(), group.by = "dxHl", dot.min = .1) + RotatedAxis()

```

# Fibroblasts  
```{r}

Idents(scaf) <- scaf$cellType
nichenet_output = nichenet_seuratobj_aggregate(
  seurat_obj = scaf, 
  receiver = "Fibroblasts", 
  condition_colname = "dxHl", condition_oi = "Dx", condition_reference = "Hlthy", 
  sender = "all", 
  ligand_target_matrix = ligand_target_matrix, lr_network = lr_network, weighted_networks = weighted_networks, organism = "mouse")

# plot target heatmap
nichenet_output$ligand_activity_target_heatmap

# Receptor interactions
nichenet_output$ligand_receptor_heatmap

# plot expression of ligands across celltypes by condition
DotPlot(scaf, features = nichenet_output$top_ligands %>% rev(), split.by = "dxHl", dot.min = .1) + RotatedAxis()

# plot expression of receptors across celltypes by condition
Idents(fibroblasts) <- fibroblasts$cellType
DotPlot(fibroblasts, features = nichenet_output$top_receptors %>% rev(), group.by = "dxHl", dot.min = .1) + RotatedAxis()

```

# T cells  
```{r, error=T}

Idents(scaf) <- scaf$cellType
nichenet_output = nichenet_seuratobj_aggregate(
  seurat_obj = scaf, 
  receiver = "T Cells", 
  condition_colname = "dxHl", condition_oi = "Dx", condition_reference = "Hlthy", 
  sender = "all", 
  ligand_target_matrix = ligand_target_matrix, lr_network = lr_network, weighted_networks = weighted_networks, organism = "mouse")

# plot target heatmap
nichenet_output$ligand_activity_target_heatmap

# Receptor interactions
nichenet_output$ligand_receptor_heatmap

# plot expression of ligands across celltypes by condition
DotPlot(scaf, features = nichenet_output$top_ligands %>% rev(), split.by = "dxHl", dot.min = .1) + RotatedAxis()

# plot expression of receptors across celltypes by condition
Idents(tcells) <- tcells$cellType
DotPlot(tcells, features = nichenet_output$top_receptors %>% rev(), group.by = "dxHl", dot.min = .1) + RotatedAxis()

```

# NK cells  
```{r, error=T}

Idents(scaf) <- scaf$cellType
nichenet_output = nichenet_seuratobj_aggregate(
  seurat_obj = scaf, 
  receiver = "NK Cells", 
  condition_colname = "dxHl", condition_oi = "Dx", condition_reference = "Hlthy", 
  sender = "all", 
  ligand_target_matrix = ligand_target_matrix, lr_network = lr_network, weighted_networks = weighted_networks, organism = "mouse")

# plot target heatmap
nichenet_output$ligand_activity_target_heatmap

# Receptor interactions
nichenet_output$ligand_receptor_heatmap

# plot expression of ligands across celltypes by condition
DotPlot(scaf, features = nichenet_output$top_ligands %>% rev(), split.by = "dxHl", dot.min = .1) + RotatedAxis()

# plot expression of receptors across celltypes by condition
Idents(nkcells) <- nkcells$cellType
DotPlot(nkcells, features = nichenet_output$top_receptors %>% rev(), group.by = "dxHl", dot.min = .1) + RotatedAxis()

```

# Monocytes  
```{r}

Idents(scaf) <- scaf$cellType
nichenet_output = nichenet_seuratobj_aggregate(
  seurat_obj = scaf, 
  receiver = "Monocytes", 
  condition_colname = "dxHl", condition_oi = "Dx", condition_reference = "Hlthy", 
  sender = "all", 
  ligand_target_matrix = ligand_target_matrix, lr_network = lr_network, weighted_networks = weighted_networks, organism = "mouse")

# plot target heatmap
nichenet_output$ligand_activity_target_heatmap

# Receptor interactions
nichenet_output$ligand_receptor_heatmap

# plot expression of ligands across celltypes by condition
DotPlot(scaf, features = nichenet_output$top_ligands %>% rev(), split.by = "dxHl", dot.min = .1) + RotatedAxis()

# plot expression of receptors across celltypes by condition
Idents(monocytes) <- monocytes$cellType
DotPlot(monocytes, features = nichenet_output$top_receptors %>% rev(), group.by = "dxHl", dot.min = .1) + RotatedAxis()

```

